[workspace]
members = [
    "aoc23",
    "aoc22",
    "aoc15"
]
resolver = "2"

# we need tests to run fast like the release build since a lot of these
# problems are very slow otherwise
[profile.test]
opt-level = 3
